### ISSUE TITLE
Removing question that already exists in different exam will cause problems

### ISSUE THREAD

**Issue by shahhaard47** [TheMightyE/CS490-Project#1]
Solution: add constructed question copy to the exam table itself so that it doesn't depend on the qBank

**Comment by debsanto** [comment]
Modified delete_question.php file.
If the question to be deleted is already included in an existing exam, then the question will not be deleted, but will be marked as archived (archived==True). If a question is marked as archived, then the question will not be returned when a call to return all questions from the questionBank is made.
Otherwise, if the question to be deleted has not yet been added to an exam, then the question's record in the questionBank will be completely deleted. 
This solves the issue of deleting questions that already exist in an exam.

**Comment by debsanto** [comment]
Also, a question will be marked as archived if it exists in an exam that a professor has already created, even if a student has not yet taken that exam.
